# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox, QTableWidgetItem
import mysql.connector


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1044, 512)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Tabs = QtWidgets.QTabWidget(self.centralwidget)
        self.Tabs.setGeometry(QtCore.QRect(10, 0, 1031, 471))
        self.Tabs.setObjectName("Tabs")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.Input1 = QtWidgets.QLineEdit(self.tab)
        self.Input1.setGeometry(QtCore.QRect(90, 130, 181, 31))
        self.Input1.setText("")
        self.Input1.setObjectName("Input1")
        self.FName = QtWidgets.QLabel(self.tab)
        self.FName.setGeometry(QtCore.QRect(150, 110, 61, 20))
        self.FName.setObjectName("FName")
        self.Title = QtWidgets.QLabel(self.tab)
        self.Title.setGeometry(QtCore.QRect(450, 10, 51, 21))
        self.Title.setObjectName("Title")
        self.Duration = QtWidgets.QLabel(self.tab)
        self.Duration.setGeometry(QtCore.QRect(720, 130, 49, 16))
        self.Duration.setObjectName("Duration")
        self.Calendar = QtWidgets.QCalendarWidget(self.tab)
        self.Calendar.setGeometry(QtCore.QRect(320, 130, 312, 190))
        self.Calendar.setObjectName("Calendar")
        self.LName = QtWidgets.QLabel(self.tab)
        self.LName.setGeometry(QtCore.QRect(150, 180, 61, 20))
        self.LName.setObjectName("LName")
        self.Book = QtWidgets.QPushButton(self.tab)
        self.Book.setGeometry(QtCore.QRect(740, 390, 81, 31))
        self.Book.setObjectName("Book")
        self.Date = QtWidgets.QLabel(self.tab)
        self.Date.setGeometry(QtCore.QRect(460, 100, 31, 20))
        self.Date.setObjectName("Date")
        self.Choice = QtWidgets.QComboBox(self.tab)
        self.Choice.setGeometry(QtCore.QRect(820, 150, 121, 31))
        self.Choice.setObjectName("Choice")
        self.Choice.addItem("")
        self.Choice.addItem("")
        self.Choice.addItem("")
        self.Choice.addItem("")
        self.Choice.addItem("")
        self.Choice.addItem("")
        self.Choice.addItem("")
        self.Choice.addItem("")
        self.Choice.addItem("")
        self.Choice.addItem("")
        self.Choice.addItem("")
        self.Input2 = QtWidgets.QLineEdit(self.tab)
        self.Input2.setGeometry(QtCore.QRect(90, 200, 181, 31))
        self.Input2.setText("")
        self.Input2.setObjectName("Input2")
        self.System = QtWidgets.QLabel(self.tab)
        self.System.setGeometry(QtCore.QRect(860, 130, 49, 16))
        self.System.setObjectName("System")
        self.Contact = QtWidgets.QLineEdit(self.tab)
        self.Contact.setGeometry(QtCore.QRect(90, 260, 181, 31))
        self.Contact.setObjectName("Contact")
        self.Time = QtWidgets.QTimeEdit(self.tab)
        self.Time.setGeometry(QtCore.QRect(690, 150, 111, 31))
        self.Time.setObjectName("Time")
        self.Email = QtWidgets.QLabel(self.tab)
        self.Email.setGeometry(QtCore.QRect(160, 240, 49, 16))
        self.Email.setObjectName("Email")
        self.Delete = QtWidgets.QPushButton(self.tab)
        self.Delete.setGeometry(QtCore.QRect(830, 390, 81, 31))
        self.Delete.setObjectName("Delete")
        self.Update = QtWidgets.QPushButton(self.tab)
        self.Update.setGeometry(QtCore.QRect(920, 390, 81, 31))
        self.Update.setObjectName("Update")
        self.Tabs.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tableWidget = QtWidgets.QTableWidget(self.tab_2)
        self.tableWidget.setGeometry(QtCore.QRect(40, 20, 750, 300))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(7)
        self.tableWidget.setRowCount(20)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        self.Tabs.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tableWidget_3 = QtWidgets.QTableWidget(self.tab_3)
        self.tableWidget_3.setGeometry(QtCore.QRect(90, 10, 451, 381))
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(4)
        self.tableWidget_3.setRowCount(20)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(3, item)
        self.Tabs.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.tab_4)
        self.tableWidget_2.setGeometry(QtCore.QRect(70, 30, 700, 400))
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(5)
        self.tableWidget_2.setRowCount(10)
        self.tableWidget_2.setColumnWidth(3, 200)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(4, item)
        self.Tabs.addTab(self.tab_4, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1044, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.Tabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.FName.setText(_translate("MainWindow", "First Name"))
        self.Title.setText(_translate("MainWindow", "Booking"))
        self.Duration.setText(_translate("MainWindow", "Duration"))
        self.LName.setText(_translate("MainWindow", "Last Name"))
        self.Book.setText(_translate("MainWindow", "Add"))
        self.Date.setText(_translate("MainWindow", "Date"))
        self.Choice.setItemText(0, _translate("MainWindow", "PC1"))
        self.Choice.setItemText(1, _translate("MainWindow", "PC2"))
        self.Choice.setItemText(2, _translate("MainWindow", "PC3"))
        self.Choice.setItemText(3, _translate("MainWindow", "PC4"))
        self.Choice.setItemText(4, _translate("MainWindow", "PC5"))
        self.Choice.setItemText(5, _translate("MainWindow", "Console1"))
        self.Choice.setItemText(6, _translate("MainWindow", "Console2"))
        self.Choice.setItemText(7, _translate("MainWindow", "Console3"))
        self.Choice.setItemText(8, _translate("MainWindow", "Console4"))
        self.Choice.setItemText(9, _translate("MainWindow", "Simulator1"))
        self.Choice.setItemText(10, _translate("MainWindow", "Simulator2"))
        self.System.setText(_translate("MainWindow", "System"))
        self.Email.setText(_translate("MainWindow", "Email"))
        self.Delete.setText(_translate("MainWindow", "Delete"))
        self.Update.setText(_translate("MainWindow", "Update"))
        self.Tabs.setTabText(self.Tabs.indexOf(self.tab), _translate("MainWindow", "Booking"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "First Name"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Last Name"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Email"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Date"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Duration"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "System"))
        self.Tabs.setTabText(self.Tabs.indexOf(self.tab_2), _translate("MainWindow", "Table"))
        item = self.tableWidget_3.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "SysID"))
        item = self.tableWidget_3.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "System"))
        item = self.tableWidget_3.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Available"))
        item = self.tableWidget_3.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Engineer"))
        self.Tabs.setTabText(self.Tabs.indexOf(self.tab_3), _translate("MainWindow", "Systems"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "First Name"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Last Name"))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Contact"))
        self.Tabs.setTabText(self.Tabs.indexOf(self.tab_4), _translate("MainWindow", "Engineers"))


def initTables():
    db = mysql.connector.connect(
        host="localhost",
        user="root",
        passwd="root",
        database="tema"
    )
    cur = db.cursor()

    cur.execute("DROP TABLE Bookings")
    cur.execute("DROP TABLE Systems")
    cur.execute("DROP TABLE Engineers")

    cur.execute("CREATE TABLE Engineers ("
               "ID SMALLINT PRIMARY KEY AUTO_INCREMENT, "
               "First_name VARCHAR(25), "
               "Last_name VARCHAR(25), "
               "Contact VARCHAR(25))")

    cur.execute("CREATE TABLE Systems ("
                "SysID SMALLINT PRIMARY KEY AUTO_INCREMENT, "
                "SystemType VARCHAR(25), "
                "Available BOOL, "
                "EngineerID SMALLINT, FOREIGN KEY(EngineerID) REFERENCES Engineers(ID))")

    cur.execute("CREATE TABLE Bookings ("
                "ID SMALLINT PRIMARY KEY AUTO_INCREMENT, "
                "First_name VARCHAR(25), "
                "Last_name VARCHAR(25), "
                "Email VARCHAR(25),"
                "BookDate DATE,"
                "Duration TIME,"
                "SystemBook SMALLINT, FOREIGN KEY(SystemBook) REFERENCES Systems(SysID))")

    cur.execute("INSERT INTO Engineers (First_name, Last_name, Contact) VALUES (%s, %s, %s)", ("John", "Doe", "johndoe@gmail.com"))
    db.commit()
    cur.execute("INSERT INTO Engineers (First_name, Last_name, Contact) VALUES (%s, %s, %s)",
                ("Bill", "Dough", "billd27@gmail.com"))
    db.commit()
    cur.execute("INSERT INTO Engineers (First_name, Last_name, Contact) VALUES (%s, %s, %s)",
                ("Alex", "Martin", "marlex@gmail.com"))
    db.commit()
    cur.execute("INSERT INTO Engineers (First_name, Last_name, Contact) VALUES (%s, %s, %s)",
                ("Andrew", "Tate", "cobratate@gmail.com"))
    db.commit()

    cur.execute("INSERT INTO Systems (SystemType, Available, EngineerID) VALUES (%s, %s, %s)", ("PC1", True, 1))
    db.commit()
    cur.execute("INSERT INTO Systems (SystemType, Available, EngineerID) VALUES (%s, %s, %s)", ("PC2", True, 1))
    db.commit()
    cur.execute("INSERT INTO Systems (SystemType, Available, EngineerID) VALUES (%s, %s, %s)", ("PC3", True, 1))
    db.commit()
    cur.execute("INSERT INTO Systems (SystemType, Available, EngineerID) VALUES (%s, %s, %s)", ("PC4", True, 2))
    db.commit()
    cur.execute("INSERT INTO Systems (SystemType, Available, EngineerID) VALUES (%s, %s, %s)", ("PC5", True, 2))
    db.commit()
    cur.execute("INSERT INTO Systems (SystemType, Available, EngineerID) VALUES (%s, %s, %s)", ("Console1", True, 3))
    db.commit()
    cur.execute("INSERT INTO Systems (SystemType, Available, EngineerID) VALUES (%s, %s, %s)", ("Console2", True, 3))
    db.commit()
    cur.execute("INSERT INTO Systems (SystemType, Available, EngineerID) VALUES (%s, %s, %s)", ("Console3", True, 3))
    db.commit()
    cur.execute("INSERT INTO Systems (SystemType, Available, EngineerID) VALUES (%s, %s, %s)", ("Console4", True, 3))
    db.commit()
    cur.execute("INSERT INTO Systems (SystemType, Available, EngineerID) VALUES (%s, %s, %s)", ("Simulator1", True, 4))
    db.commit()
    cur.execute("INSERT INTO Systems (SystemType, Available, EngineerID) VALUES (%s, %s, %s)", ("Simulator2", True, 4))
    db.commit()


def initUI():
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    for x in range(1,12):
        ui.tableWidget_3.setItem(x-1, 0, QTableWidgetItem(str(x)))
        ui.tableWidget_3.setItem(x-1,2, QTableWidgetItem("Yes"))

    ui.tableWidget_3.setItem(0, 1, QTableWidgetItem('PC1'))
    ui.tableWidget_3.setItem(1, 1, QTableWidgetItem('PC2'))
    ui.tableWidget_3.setItem(2, 1, QTableWidgetItem('PC3'))
    ui.tableWidget_3.setItem(3, 1, QTableWidgetItem('PC4'))
    ui.tableWidget_3.setItem(4, 1, QTableWidgetItem('PC5'))
    ui.tableWidget_3.setItem(5, 1, QTableWidgetItem('Console1'))
    ui.tableWidget_3.setItem(6, 1, QTableWidgetItem('Console2'))
    ui.tableWidget_3.setItem(7, 1, QTableWidgetItem('Console3'))
    ui.tableWidget_3.setItem(8, 1, QTableWidgetItem('Console4'))
    ui.tableWidget_3.setItem(9, 1, QTableWidgetItem('Simulator1'))
    ui.tableWidget_3.setItem(10, 1, QTableWidgetItem('Simulator2'))

    ui.tableWidget_3.setItem(0, 3, QTableWidgetItem('1'))
    ui.tableWidget_3.setItem(1, 3, QTableWidgetItem('1'))
    ui.tableWidget_3.setItem(2, 3, QTableWidgetItem('1'))
    ui.tableWidget_3.setItem(3, 3, QTableWidgetItem('2'))
    ui.tableWidget_3.setItem(4, 3, QTableWidgetItem('2'))
    ui.tableWidget_3.setItem(5, 3, QTableWidgetItem('3'))
    ui.tableWidget_3.setItem(6, 3, QTableWidgetItem('3'))
    ui.tableWidget_3.setItem(7, 3, QTableWidgetItem('3'))
    ui.tableWidget_3.setItem(8, 3, QTableWidgetItem('3'))
    ui.tableWidget_3.setItem(9, 3, QTableWidgetItem('4'))
    ui.tableWidget_3.setItem(10, 3, QTableWidgetItem('4'))


    for x in range(1, 5):
        ui.tableWidget_2.setItem(x - 1, 0, QTableWidgetItem(str(x)))

    ui.tableWidget_2.setItem(0, 1, QTableWidgetItem("John"))
    ui.tableWidget_2.setItem(0, 2, QTableWidgetItem("Doe"))
    ui.tableWidget_2.setItem(0, 3, QTableWidgetItem("johndoe@gmail.com"))
    ui.tableWidget_2.setItem(1, 1, QTableWidgetItem("Bill"))
    ui.tableWidget_2.setItem(1, 2, QTableWidgetItem("Dough"))
    ui.tableWidget_2.setItem(1, 3, QTableWidgetItem("billd27@gmail.com"))
    ui.tableWidget_2.setItem(2, 1, QTableWidgetItem("Alex"))
    ui.tableWidget_2.setItem(2, 2, QTableWidgetItem("Martin"))
    ui.tableWidget_2.setItem(2, 3, QTableWidgetItem("marlex@gmail.com"))
    ui.tableWidget_2.setItem(3, 1, QTableWidgetItem("Andrew"))
    ui.tableWidget_2.setItem(3, 2, QTableWidgetItem("Tate"))
    ui.tableWidget_2.setItem(3, 3, QTableWidgetItem("cobratate@gmail.com"))

    ui.Book.clicked.connect(show_popup)


def show_popup():
    msg = QMessageBox()
    msg.setWindowTitle("Result")
    msg.setText("Success")
    msg.setIcon(QMessageBox.Information)
    msg.exec_()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    initUI()
    initTables()
    MainWindow.show()
    sys.exit(app.exec_())
