INSERT INTO Engineers (First_name, Last_name, Contact) VALUES ("John", "Doe", "johndoe@gmail.com");
INSERT INTO Engineers (First_name, Last_name, Contact) VALUES ("Bill", "Dough", "billd27@gmail.com");
INSERT INTO Engineers (First_name, Last_name, Contact) VALUES ("Alex", "Martin", "marlex@gmail.com");
INSERT INTO Engineers (First_name, Last_name, Contact) VALUES ("Andrew", "Daniel", "dandrew@gmail.com");
INSERT INTO Systems (SystemType, Available, EngineerID) VALUES("PC1", True, 1);
INSERT INTO Systems (SystemType, Available, EngineerID) VALUES("PC2", True, 1);
INSERT INTO Systems (SystemType, Available, EngineerID) VALUES("PC3", True, 1);
INSERT INTO Systems (SystemType, Available, EngineerID) VALUES("PC4", True, 2);
INSERT INTO Systems (SystemType, Available, EngineerID) VALUES("PC5", True, 2);
INSERT INTO Systems (SystemType, Available, EngineerID) VALUES("Console1", True, 3);
INSERT INTO Systems (SystemType, Available, EngineerID) VALUES("Console2", True, 3);
INSERT INTO Systems (SystemType, Available, EngineerID) VALUES("Console3", True, 3);
INSERT INTO Systems (SystemType, Available, EngineerID) VALUES("Console4", True, 3);
INSERT INTO Systems (SystemType, Available, EngineerID) VALUES("Simulator1", True, 4);
INSERT INTO Systems (SystemType, Available, EngineerID) VALUES("Simulator2", True, 4);
